# Generated by Django 6.0.6 on 2026-06-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('classe', models.CharField(choices=[('1', 'Classe 1 - Comptes de ressources durables'), ('2', "Classe 2 - Comptes d'actif immobilisé"), ('3', 'Classe 3 - Comptes de stocks'), ('4', 'Classe 4 - Comptes de tiers'), ('5', 'Classe 5 - Comptes de trésorerie'), ('6', 'Classe 6 - Comptes de charges'), ('7', 'Classe 7 - Comptes de produits')], max_length=1)),
                ('solde_debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('solde_credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Compte Comptable',
                'verbose_name_plural': 'Plan Comptable SYSCOHADA',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('type_journal', models.CharField(choices=[('AC', 'Achats'), ('VT', 'Ventes'), ('BQ', 'Banque'), ('CA', 'Caisse'), ('OD', 'Opérations Diverses')], max_length=2)),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journaux Comptables',
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numero_piece', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=200)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.comptecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comptabilite.journal')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
                'ordering': ['-date', 'numero_piece'],
            },
        ),
    ]
