# Generated by Django 6.0.6 on 2026-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0002_client_entreprise_facture_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='date_suppression',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='est_supprime',
            field=models.BooleanField(default=False),
        ),
    ]
