# Generated by Django 6.0.6 on 2026-06-09 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entreprises', '0001_initial'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produit',
            name='entreprise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entreprises.entreprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produit',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='produit',
            unique_together={('entreprise', 'code')},
        ),
    ]
